Create db
miraikeitai2020/ap1_Resns_backend pull request #4
Opened 2020-10-02 16:54 UTC by take-2405

[概要]
DBのtable定義について今1度考え直しました。

[変更内容]
tableの定義をしているinit.sqlの内容を変更しました。(ほぼ全てのテーブル)
docker-compose.yamlのDB以外の記述があったのですが、無駄だったため省きました。

[レビューして欲しいところ(あれば)]
必要のない要素はないか
きちんと正しい命名をすることができているか

2020-10-02 18:57 UTC, b1018043 reviewed
たいていのコメントは修正は任意です。  
少なくともタイポは直した方がいいと思います。

2020-10-02 18:57 UTC, tmrkw1497 commented on db/mysql/init/init.sql
> +`ageYaer` int NOT NULL COMMENT '年代(年)',
ここ2つだけローワーキャメルケースなのが気になる

2020-10-02 18:57 UTC, tmrkw1497 commented on README.md
> +
README.md apiの起動の仕方とかを記載するとレビュワーに優しいですね(現状で修正する必要はないと思う)

2020-10-02 18:57 UTC, tmrkw1497 commented on db/mysql/init/init.sql
> +-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
設計書のデータ設計とだいぶ異なっているので設計書修正しないといけないですね

2020-10-02 18:57 UTC, b1018043 commented on db/mysql/init/init.sql
> +`yaer` int NOT NULL COMMENT '生年月日(年)',
typo year

2020-10-02 18:57 UTC, b1018043 commented on db/mysql/init/init.sql
> +`ageYaer` int NOT NULL COMMENT '年代(年)',
typo year

2020-10-02 18:57 UTC, b1018043 commented on docker-compose.yaml
> +      MYSQL_ROOT_PASSWORD: 'rootpassword'
あんまりサーバー側のことわからないけどパスワード?をパブリックなリポジトリに書くのは大丈夫?

2020-10-02 18:57 UTC, b1018043 commented on db/mysql/init/init.sql
> +`listData_id` VARCHAR(64) NOT NULL COMMENT '識別ID',
キャメルケースとスネークケースが混ざっているのが気になる

2020-10-02 18:57 UTC, b1018043 commented on db/mysql/init/init.sql
> +`user_id` VARCHAR(32) NOT NULL COMMENT 'ユーザID',
`user_id`は他のところでは`VARCHAR(64)`になってるけど大丈夫?

2020-10-02 18:57 UTC, b1018043 commented on db/mysql/init/init.sql
> +`comments_id` VARCHAR(64) NOT NULL COMMENT 'コメントのID',
なぜ複数形?(`comments_id`)

2020-10-02 18:57 UTC, b1018043 commented on db/mysql/init/init.sql
> +`comments_contents` VARCHAR(64) NOT NULL COMMENT 'コメントの内容',
記事の内容は`context`だったけどなんで違うの?

2020-10-02 18:57 UTC, b1018043 commented on db/mysql/init/init.sql
> +`comments_id` VARCHAR(64) NOT NULL COMMENT 'コメントのID',
もしかして所有格?

2020-10-02 18:57 UTC, b1018043 commented on db/mysql/init/init.sql
> +`comments_contents` VARCHAR(64) NOT NULL COMMENT 'コメントの内容',
`comments_context`では?

2020-10-02 18:57 UTC, b1018043 commented on db/mysql/init/init.sql
> +CREATE TABLE IF NOT EXISTS `resns_app`.`users_tags` (
見た感じユーザの興味のあるジャンルを保存しているように見えますが、名前が`users_tags`なのが気になります

2020-10-02 18:57 UTC, b1018043 commented on db/mysql/init/init.sql
> +`article_tag` VARCHAR(32) NOT NULL COMMENT '記事のタグ',
`article_tag`だとどう言ったデータが入っているのかわかりにくいので`tag_name`とかにしてもいいかも

2020-10-02 18:57 UTC, b1018043 commented on db/mysql/init/init.sql
> +`user_image` VARCHAR(128) NOT NULL COMMENT 'ユーザーの画像',
`user_id`あるなら`users`のテーブルから持ってこれないの?

2020-10-02 18:57 UTC, b1018043 commented on db/mysql/init/init.sql
> +PRIMARY KEY (`article_id`)
これ記事のいいねを管理しているテーブルなら`nice_id`をPRIMARY KEYにするべきでは?

2020-10-02 18:57 UTC, b1018043 commented on db/mysql/init/init.sql
> +PRIMARY KEY (`article_id`)
これ記事のコメントを管理しているテーブルなら`comments_id`をPRIMARY KEYにするべきでは?

2020-10-02 21:34 UTC, SaKu2110 commented on db/mysql/init/init.sql
> +-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
[優先度 低]もしそのDBやテーブルがあったら削除（drop）するSQL忍ばせると新設設計ですよ

2020-10-02 22:20 UTC, SaKu2110 requested changes
気になって眠れないところだけコメントしました

2020-10-02 22:20 UTC, SaKu2110 commented on db/mysql/init/init.sql
> +CREATE TABLE IF NOT EXISTS `resns_app`.`users` (
[優先度 低]単純にサービスが使うDBの命名規則はap1かresnsなのかで気になった

2020-10-02 22:20 UTC, SaKu2110 commented on db/mysql/init/init.sql
> +CREATE TABLE IF NOT EXISTS `resns_app`.`users` (
`users`テーブルなので`user_`はいらないかと思われ（テーブル名でわかる）

2020-10-02 22:20 UTC, SaKu2110 commented on db/mysql/init/init.sql
> +CREATE TABLE IF NOT EXISTS `resns_app`.`users_info` (
ここサービスごとに作らないです

2020-10-02 22:20 UTC, SaKu2110 commented on db/mysql/init/init.sql
> +CREATE TABLE IF NOT EXISTS `resns_app`.`users` (
以下全て同じ

2020-10-02 22:20 UTC, SaKu2110 commented on db/mysql/init/init.sql
> +`nice_id` VARCHAR(64) NOT NULL COMMENT 'NiceID',
`nice_id`の用途がわからん

2020-10-02 22:20 UTC, SaKu2110 commented on db/mysql/init/init.sql
> +`genre` int NOT NULL COMMENT 'ジャンル',
grnreをPRIMARY KEYにしなかった理由はなぜ？
user_idだと1ユーザー１タグしかつけられないと思う...

2020-10-02 22:20 UTC, SaKu2110 commented on db/mysql/init/init.sql
> +`listData_id` VARCHAR(64) NOT NULL COMMENT '識別ID',
1ユーザー1リストなら`listData_id`いらない気がする

2020-10-02 22:20 UTC, SaKu2110 commented on db/mysql/init/init.sql
> +`listData_id` VARCHAR(64) NOT NULL COMMENT '識別ID',
`user_id`で識別可能じゃない？

2020-10-03 01:22 UTC, take-2405 commented on db/mysql/init/init.sql
> +`ageYaer` int NOT NULL COMMENT '年代(年)',
変更しました

2020-10-03 01:23 UTC, take-2405 commented on db/mysql/init/init.sql
> +-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
そうだね、多分これからも変わります。

2020-10-03 01:24 UTC, take-2405 commented on db/mysql/init/init.sql
> +CREATE TABLE IF NOT EXISTS `resns_app`.`users_tags` (
あざす

2020-10-03 01:50 UTC, take-2405 commented on db/mysql/init/init.sql
> +PRIMARY KEY (`article_id`)
マジそれ

2020-10-03 01:51 UTC, take-2405 commented on db/mysql/init/init.sql
> +PRIMARY KEY (`article_id`)
マジそれ

2020-10-03 01:51 UTC, take-2405 commented on docker-compose.yaml
> +      MYSQL_ROOT_PASSWORD: 'rootpassword'
問題ないはず、、、

2020-10-03 01:54 UTC, take-2405 commented on db/mysql/init/init.sql
> +`article_tag` VARCHAR(32) NOT NULL COMMENT '記事のタグ',
個人的には記事のタグだからarticle_tags派なんですけど

2020-10-03 02:16 UTC, take-2405 commented on db/mysql/init/init.sql
> +CREATE TABLE IF NOT EXISTS `resns_app`.`users` (
resnsで行きます

2020-10-03 02:19 UTC, take-2405 commented on db/mysql/init/init.sql
> +CREATE TABLE IF NOT EXISTS `resns_app`.`users_info` (
開発する時に必要だと思うので残しておきます。

2020-10-03 02:20 UTC, take-2405 commented on db/mysql/init/init.sql
> +`genre` int NOT NULL COMMENT 'ジャンル',
genreはprimary keynにはできない(userが同じジャンルを洗濯するため)
テーブルを変更し、タグを4つ保存するようにしました。

2020-10-03 02:21 UTC, take-2405 commented on db/mysql/init/init.sql
> +`nice_id` VARCHAR(64) NOT NULL COMMENT 'NiceID',
他の要素(記事のID、ユーザーID)は重複する可能性があり、primary keyに指定できないため作成しました。

2020-10-03 02:29 UTC, take-2405 commented on db/mysql/init/init.sql
> +`listData_id` VARCHAR(64) NOT NULL COMMENT '識別ID',
user_idをprimary keyにするとlistに記事1つしか入れられない
primary keyなしっていうのは個人的にはあまりしたくはない

2020-10-03 02:29 UTC, take-2405 commented on db/mysql/init/init.sql
> +`user_image` VARCHAR(128) NOT NULL COMMENT 'ユーザーの画像',
外部きーってことであってる？

2020-10-03 03:01 UTC, b1018043 commented on db/mysql/init/init.sql
> +`article_tag` VARCHAR(32) NOT NULL COMMENT '記事のタグ',
63行の話です

2020-10-03 03:01 UTC, b1018043 commented on db/mysql/init/init.sql
> +`user_image` VARCHAR(128) NOT NULL COMMENT 'ユーザーの画像',
yes

2020-10-03 07:59 UTC, tmrkw1497 commented on db/mysql/init/init.sql
> +`age_yaer` int NOT NULL COMMENT '年代(年)',
typo "year"に修正

2020-10-03 08:30 UTC, SaKu2110 commented on db/mysql/init/init.sql
> +`listData_id` VARCHAR(64) NOT NULL COMMENT '識別ID',
理解した

2020-10-03 10:55 UTC, merged